
select c.contextid
     , c.contextname
     , c.contextparentcontextid
     , c.clientid
     , c.createddatetime
     , c.createdby
     , c.lastname
     , c.plclastname
     , c.firstname
     , c.plcfirstname
     , c.middleinitial
     , c.plcmiddleinitial
     , c.previouslastname
     , c.plcpreviouslastname
     , c.mothersmaidenname
     , c.namesuffix
     , c.plcnamesuffix
     , c.preferredname
     , c.plcpreferredname
     , c.registrationdatedatetime
     , c.address1
     , c.plcaddress1
     , c.address2
     , c.plcaddress2
     , c.city
     , c.plccity
     , c.state
     , c.zip
     , c.homephone
     , c.translatedhomephoneindex
     , c.workphone
     , c.translatedworkphoneindex
     , c.otherphonetype
     , c.otherphone
     , c.dobdatetime
     , c.ssn
     , c.sex
     , c.sexunknownyn
     , c.registrationdepartmentid
     , c.currentdepartmentid
     , c.primaryproviderid
     , c.maritalstatusid
     , c.studentstatusid
     , c.employmentstatusid
     , c.deceaseddatedatetime
     , c.employername
     , c.educationlevelid
     , c.referralsourceid
     , c.referralsourceother
     , c.ethnicityid
     , c.raceid
     , c.primarylanguageid
     , c.primarylanguageother
     , c.transferdatedatetime
     , c.status
     , c.notes
     , c.contactname
     , c.contactname2
     , c.contactrelationship
     , c.contactphone1
     , c.contactphone2
     , c.nextkinname
     , c.nextkinrelationship
     , c.nextkinphone
     , c.rpfirstname
     , c.rplastname
     , c.rpmiddleinitial
     , c.rpdobdatetime
     , c.guardianfirstname
     , c.guardianlastname
     , c.guardianmiddleinitial
     , c.referringproviderid
     , c.email
     , c.directemail
     , c.emailexistsyn
     , c.emailconfirmeddatetime
     , c.lastemail
     , c.suppressstatement
     , c.onlinestatementonlyyn
     , c.onlinestatementonlydatedatetime
     , c.nextstatementdatedatetime
     , c.statementnote
     , c.balanceforwardamount
     , c.unappliedamount
     , c.employercity
     , c.employeraddress
     , c.employerstate
     , c.employerzip
     , c.employercountryid
     , c.employerphone
     , c.occupationid
     , c.occupation
     , c.industryid
     , c.industry
     , c.diagnosis1
     , c.diagnosis2
     , c.diagnosis3
     , c.lastmodifieddatetime
     , c.lastmodifiedby
     , c.firstvisitdatedatetime
     , c.creditbalance
     , c.newpatientid
     , c.outstandingp
     , c.claimstatusp
     , c.holdstatementreason
     , c.otherrecordnumber
     , c.overduedatedatetime
     , c.familyclientid
     , c.idoverriddenyn
     , c.importuniqueid
     , c.importcol1
     , c.importcol2
     , c.employerid
     , c.enterpriseid
     , c.rpaddress
     , c.rpcity
     , c.rpstate
     , c.rpzip
     , c.originalpracticeid
     , c.charthome
     , c.chartlocation
     , c.chartholder
     , c.countryid
     , c.rpcountryid
     , c.privacynoticegivenflag
     , c.privacynoticegivendatedatetime
     , c.privacynoticenotgivenreason
     , c.privacynoticenotgivennote
     , c.privacynoticegivendepartmentid
     , c.privacynoticegivenby
     , c.patientsignatureonfileflag
     , c.patientsignatureeffectivedatedatetime
     , c.patientsignatureexpirationdatedatetime
     , c.insuredsignatureonfileflag
     , c.insuredsignatureeffectivedatedatetime
     , c.insuredsignatureexpirationdatedatetime
     , c.consenttocallflag
     , c.consenttocallflageffectivedatedatetime
     , c.selfpayrestrictionyn
     , c.signaturesourcecode
     , c.restrictrecordyn
     , c.confidentialcommunicationyn
     , c.blockpatientyn
     , c.restrictreportingyn
     , c.medicationhistoryconsentby
     , c.medicationhistoryconsentdatedatetime
     , c.medicationhistoryconsentyn
     , c.providergroupid
     , c.hipaaid
     , c.homeboundyn
     , c.rpnamesuffix
     , c.rpaddress2
     , c.guardiannamesuffix
     , c.mobilephone
     , c.hasmobileyn
     , c.translatedmobilephoneindex
     , c.mobilecarrierid
     , c.rpssn
     , c.rpphone
     , c.rpemployerid
     , c.sameaddressflag
     , c.relationshiptopatientid
     , c.statementnoteeffectivedatedatetime
     , c.statementnoteexpirationdatedatetime
     , c.defaultprescriptionproviderid
     , c.defaultlabproviderid
     , c.defaultimagingproviderid
     , c.licensenumber
     , c.licensestateid
     , c.licenseexpirationdatedatetime
     , c.pincode
     , c.encryptedpincode
     , c.encryptedpincodesalt
     , c.donotcallyn
     , c.noportalyn
     , c.noportaladoptionemailyn
     , c.portalaccessyn
     , c.portalaccessprovideddatetime
     , c.portaltermsonfileflag
     , c.portaltermseffectivedatedatetime
     , c.portaltermsexpirationdatedatetime
     , c.portalregistrationdatedatetime
     , c.quickpaytermsonfileflag
     , c.quickpaytermseffectivedatedatetime
     , c.quickpaytermsexpirationdatedatetime
     , c.smsoptindatedatetime
     , c.smsprompteddatedatetime
     , c.consenttotextyn
     , c.contactpreference
     , c.hiesubmissionyn
     , c.hiesubmissiondatedatetime
     , c.hiesubmissionby
     , c.hieretrievalyn
     , c.hieretrievaldatedatetime
     , c.hieretrievalby
     , c.rpemail
     , c.familysize
     , c.unconfirmedfamilysize
     , c.unconffamilysizedeclinedyn
     , c.yearlyincome
     , c.unconfirmedyearlyincome
     , c.incomeperpayperiod
     , c.unconfirmedincomeperpayperiod
     , c.payperiod
     , c.unconfirmedpayperiod
     , c.unconfirmedincomedeclinedyn
     , c.unconfirmedfederalpovertylevel
     , c.agriworker
     , c.agriworkertypes
     , c.homeless
     , c.homelesstypes
     , c.veteranstatus
     , c.schoolbased
     , c.publichousing
     , c.rpemailexistsyn
     , c.shownewfeatureportalyn
     , c.phonemessageokyn
     , c.contacttimeid
     , c.directoryyn
     , c.organdonoryn
     , c.altcontactname
     , c.altcontactphone
     , c.religionid
     , c.church
     , c.caresummarydeliverypreference
     , c.testpatientyn
     , c.streamlinedtestpatientyn
     , c.streamlinedtestusername
     , c.unconfincomerangedeclinedyn
     , c.sexualorientation
     , c.sexualorientationother
     , c.sexualorientationid
     , c.genderidentity
     , c.genderidentityother
     , c.genderidentityid
     , c.altfirstname
     , c.plcaltfirstname
     , c.preferredpronouns
     , c.assignedsexatbirth
     , c.norpfirstnameyn
     , c.norplastnameyn
     , c.johndoeyn
     , c.lastupdated
from {{ source('athena','CLIENT') }} as c
