
select c.contextid
     , c.contextname
     , c.contextparentcontextid
     , c.claimid
     , c.originalclaimid
     , c.patientid
     , c.claimprimarypatientinsid
     , c.claimsecondarypatientinsid
     , c.claimschedulingproviderid
     , c.renderingproviderid
     , c.supervisingproviderid
     , c.claimappointmentid
     , c.patientdepartmentid
     , c.servicedepartmentid
     , c.claimreferringproviderid
     , c.claimreferralauthid
     , c.patientroundinglistid
     , c.primaryclaimstatus
     , c.secondaryclaimstatus
     , c.patientclaimstatus
     , c.primaryoutstanding
     , c.secondaryoutstanding
     , c.patientoutstanding
     , c.relatedtoemploymentyn
     , c.relatedtoautoaccidentyn
     , c.medicaidresubmissioncode
     , c.primaryclaimtype
     , c.secondaryclaimtype
     , c.claimcreateddatetime
     , c.createdby
     , c.claimservicedate
     , c.hospitalizationfromdate
     , c.hospitalizationtodate
     , c.reserved19
     , c.paytotaxid1
     , c.paytotaxid2
     , c.lastmodified
     , c.lastmodifiedby
     , c.acceptassignmentyn1
     , c.acceptassignmentyn2
     , c.accidentdate
     , c.additionalfreetext
     , c.alternativepaymentmodelid
     , c.anotherpartyresponsibleyn
     , c.assignmentofbenefitsflag
     , c.autoaccidentstate
     , c.claimalarmeligibleyn
     , c.claimbatchid
     , c.claimpatientinsurancepid
     , c.claimsubmissioncategoryid1
     , c.claimsubmissioncategoryid2
     , c.claimtype
     , c.coveragescanyn
     , c.currentillnessdate
     , c.diagnosis1
     , c.diagnosis2
     , c.diagnosis3
     , c.diagnosis4
     , c.diagnosis5
     , c.diagnosis6
     , c.diagnosis7
     , c.diagnosis8
     , c.epaymentcontractid
     , c.fromunabletoworkdate
     , c.fullyworkedreasonid1
     , c.fullyworkedreasonid2
     , c.fullyworkedreasonidp
     , c.healthcareclaimtypeid1
     , c.healthcareclaimtypeid2
     , c.lastaction
     , c.lastactiondate
     , c.lastbilleddate1
     , c.lastbilleddate2
     , c.lastbilleddatep
     , c.lastscrubdate1
     , c.lastscrubdate2
     , c.lastscrubdatep
     , c.manualdropreasonid
     , c.manualdropreasonid2
     , c.manualdropyn
     , c.manualdropyn2
     , c.medicaidresubmissionorigrefno
     , c.mspinsurancetypeid
     , c.mspinsurancetypesetyn
     , c.nodenialmanagementyn
     , c.otherdiagnoses
     , c.parentclaimid
     , c.paytonpi1
     , c.paytonpi2
     , c.physiciansignaturedate
     , c.pqriparticipation
     , c.primarybillingproviderid
     , c.printzerodollarchargesyn1
     , c.relatedtootheraccidentyn
     , c.releaseofinformationyn1
     , c.reserved10d
     , c.retromedicaidenrollmentyn
     , c.rtaeligibleyn1
     , c.signaturesourcecode
     , c.similarillnessdate
     , c.slidingfeepatientinsuranceid
     , c.status1claimnoteid
     , c.status1lastmodified
     , c.status2claimnoteid
     , c.status2lastmodified
     , c.statuspclaimnoteid
     , c.statusplastmodified
     , c.tounabletoworkdate
     , c.visitbillid
     , c.visitgroupid
     , c.lastupdated

from {{ source('athena','CLAIM' ) }} as c
where c.primaryclaimstatus = 'CLOSED'
