select p.contextid
     , p.contextname
     , p.contextparentcontextid
     , p.patientid
     , p.defaultimagingproviderid
     , p.familyid
     , p.enterpriseid
     , p.firstname
     , p.lastname
     , p.middleinitial
     , p.namesuffix
     , p.sex
     , p.dob
     , p.address
     , p.address2
     , p.city
     , p.state
     , p.zip
     , p.patientemployerid
     , p.patienthomephone
     , p.workphone
     , p.mobilephone
     , p.contactpreference
     , p.email
     , p.donotcallyn
     , p.ethnicity
     , p.cdcethnicitycode
     , p.race
     , p.cdcracecode
     , p.language
     , p.iso6392code
     , p.maritalstatus
     , p.smsoptindate
     , p.deceaseddate
     , p.patientstatus
     , p.holdstatementreason
     , p.newpatientid
     , p.registrationdate
     , p.primaryproviderid
     , p.preferredlabid
     , p.selfpayrestrictionyn
     , p.occupation
     , p.referralsource
     , p.referralsourceother
     , p.guarantorfirstname
     , p.guarantorlastname
     , p.guarantormiddleinitial
     , p.guarantornamesuffix
     , p.guarantordob
     , p.guarantorssn
     , p.guarantorrelationship
     , p.guarantoraddress
     , p.guarantoraddress2
     , p.guarantorcity
     , p.guarantorstate
     , p.guarantorzip
     , p.guarantoremail
     , p.guarantoremployerid
     , p.guardianfirstname
     , p.guardianlastname
     , p.guardianmiddleinitial
     , p.guardiannamesuffix
     , p.emergencycontactname
     , p.emergencycontactrelationship
     , p.emergencycontactphone
     , p.patientssn
     , p.registrationdepartmentid
     , p.currentdepartmentid
     , p.providergroupid
     , p.unconfirmedfamilysize
     , p.unconfincomeperpayperiod
     , p.unconfirmedpayperiod
     , p.unconfirmedyearlyincome
     , p.unconfirmedpovertylevel
     , p.unconfirmedfamilyszedeclyn
     , p.unconfirmedincomedeclinedyn
     , p.guarantorphone
     , p.agriculturalworker
     , p.agriculturalworkertypes
     , p.homelessstatus
     , p.homelessstatustypes
     , p.schoolbasedhealthcenterpnt
     , p.veteranstatus
     , p.testpatientyn
     , p.privacynoticegivenflag
     , p.privacynoticegivendate
     , p.privacynoticegivendeptid
     , p.privacynoticegivenby
     , p.privnoticenotgivenreason
     , p.privnoticenotgivennote
     , p.patientsigonfileflag
     , p.patientsigeffectivedate
     , p.patientsigexpirationdate
     , p.insuredsigonfileflag
     , p.insuredsigeffectivedate
     , p.insuredsigexpirationdate
     , p.consenttocallflag
     , p.consenttocalleffdate
     , p.genderidentity
     , p.sexualorientation
     , p.consenttotextyn
     , p.publichousing
     , p.defaultprescriptionprovid
     , p.restrictreportingyn
     , p.translatedhomephoneindex
     , p.translatedmobilephoneindex
     , p.translatedworkphoneindex
     , p.assignedsexatbirth
     , p.deletedby
     , p.deleteddatetime
     , p.lastupdated

from {{ source('athena','PATIENT') }} as p
where p.deletedby is null and p.deleteddatetime is null
