select d.contextid
     , d.contextname
     , d.contextparentcontextid
     , d.documentid
     , d.patientid
     , d.chartid
     , d.departmentid
     , d.clinicalencounterid
     , d.createdclinicalencounterid
     , d.orderdocumentid
     , d.clinicalproviderid
     , d.appointmentid
     , d.documentclass
     , d.documentsubclass
     , d.documentpreclass
     , d.documentcategory
     , d.documentsubject
     , d.delegatesignedoffby
     , d.needsproviderdelegateackyn
     , d.clinicalordertype
     , d.clinicalordertypegroup
     , d.fbdmedid
     , d.clinicalproviderordertype
     , d.clinicalordergenus
     , d.status
     , d.providerusername
     , d.cvx
     , d.vaccineroute
     , d.priority
     , d.assignedto
     , d.notifier
     , d.source
     , d.route
     , d.specimendescription
     , d.specimencollectedby
     , d.specimencollecteddatetime
     , d.specimendrawlocation
     , d.specimensource
     , d.alarmdays
     , d.alarmdate
     , d.imageexistsyn
     , d.orderdatetime
     , d.createddatetime
     , d.createdby
     , d.receiveddatetime
     , d.reviewedby
     , d.revieweddatetime
     , d.observationdatetime
     , d.deactivateddatetime
     , d.deactivatedby
     , d.futuresubmitdatetime
     , d.denieddatetime
     , d.deniedby
     , d.documenttextdata
     , d.approveddatetime
     , d.approvedby
     , d.deleteddatetime
     , d.deletedby
     , d.ordertext
     , d.providernote
     , d.patientnote
     , d.externalnote
     , d.resultnotes
     , d.interfacevendorname
     , d.outofnetworkrefreasonname
     , d.exactduplicatedocumentid
     , d.airlockyn
     , d.ordering
     , d.callbackname
     , d.callbacknumber
     , d.callbacknumbertype
     , d.clientbill
     , d.clinicalencounterdate
     , d.clinicalepisodeid
     , d.clinicalpaperformid
     , d.clinicalproviderordertypeid
     , d.confidentialyn
     , d.consentdocumentid
     , d.containsresultqualityimageyn
     , d.cosignature1by
     , d.cosignature1timestamp
     , d.cosignature2by
     , d.cosignature2timestamp
     , d.customordercode
     , d.defaultsource
     , d.defaultsourceid
     , d.discussedby
     , d.discussedtimestamp
     , d.documentationonlyyn
     , d.documentbarcodeid
     , d.documenterroractionid
     , d.documentlabeltext
     , d.documentprocessingruleid
     , d.documentsubmissionbatchid
     , d.documentworkflowname
     , d.duplicategroup
     , d.errorflag
     , d.faxgroupid
     , d.faxworkflowcaptureresultid
     , d.forcedoubledataentry
     , d.foreigndocumentnumber
     , d.fromfaxnumber
     , d.fromremote
     , d.fulfillsorderchecklistvalueid
     , d.globalclinicalpaperformid
     , d.historicalyn
     , d.imagefilelink
     , d.imagegroupid
     , d.incomingstatus
     , d.inptstayid
     , d.interfacemessageid
     , d.interfacevendorid
     , d.internalinterpretation
     , d.internaltext
     , d.inunconfiguredbucketyn
     , d.newdosage
     , d.newrxname
     , d.nonathenayn
     , d.numprescriptions
     , d.observationtimeentered
     , d.ocrpriority
     , d.ocrstatus
     , d.ocrtemplateid
     , d.ocrtemplateprocessingtime
     , d.offmenuyn
     , d.orderinvoiceyn
     , d.outboundyn
     , d.outofnetworkreferralreasonid
     , d.parentorderdocumentid
     , d.parentrequisitionid
     , d.patientcaseid
     , d.patientdob
     , d.patientfacingstatus
     , d.performingprovider
     , d.persistenceyn
     , d.practicefaxid
     , d.presigned
     , d.processingholdtimestamp
     , d.providerdelegateack
     , d.providerdelegator
     , d.schedulewithin
     , d.specialtyid
     , d.versiontoken
     , d.splitbypatient
     , d.standingcancelled
     , d.standingcancelledby
     , d.standingdurationdays
     , d.standingdurationmonths
     , d.standingfrequencydays
     , d.standingfrequencymonths
     , d.standingorderdocumentid
     , d.standingorderforeignid
     , d.standingstartdate
     , d.supersededdocumentid
     , d.supervisingproviderid
     , d.tietoforeigndocumentnumber
     , d.clinicalordertypeid
     , d.lastsubmittedby
     , d.lastsubmittedtimestamp
     , d.lastupdated
from {{ source('athena','DOCUMENT') }} as d
where d.deleteddatetime is null and d.deletedby is null
